### ISSUE TITLE
build

### ISSUE THREAD

**Issue by greatathrun** [bytesandbrains/h3-pg#1]
I got the dll by visual studio.But the pgadmin show me a label " could find the function 'h3ndex_in'" when i am creating extension in postgreSQL!

**Comment by zachasme** [comment]
Can you explain the steps you took?

Have you tried installing using [pgxnclient](https://pypi.org/project/pgxnclient/)?

```
$ pgxn install h3
$ pgxn load -d mydb h3
$ psql -d mydb
```
