### ISSUE TITLE
Unable to install/compile the extension on Ubuntu 22.04 + Postgres 15.3

### ISSUE THREAD

**Issue by asitemade4u** [bytesandbrains/h3-pg#132]
Hi,

- I am trying to install the extension as per your instructions (`pgxn install h3`)
- I have installed all required tools to compile (`git`, `build-essential`, etc.)
- I have also cloned the source in case I would need to compile it myself.

In both cases (either through `pxn` or through my own compilation) I get this error ;

```log
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY) (found version
  "15.3")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPostgreSQL.cmake:119 (find_package_handle_standard_args)
  CMakeLists.txt:49 (find_package)
```
 I checked the code in `FindPostgreSQL.cmake` and confirmed that you are indeed allowing compilation against Postgres 15.

How come Postgres cannot be found during the compilation process? What am I doing wrong?

Best,
Stephen

**Comment by jgbob** [comment]
Hi. Try to install postgresql15-dev package

**Comment by zachasme** [comment]
Hi @asitemade4u, glad you found a solution! For future reference, it might be possible to force the postgres major version by setting a POSTGRESQL_VERSION=14 environment variable before running cmake.
