### ISSUE TITLE
h3-pg vs pgh3

### ISSUE THREAD

**Issue by tarnh** [bytesandbrains/h3-pg#14]
Is your piece of software better than https://github.com/dlr-eoc/pgh3 ?
I have to figure out which one to use.

**Comment by zachasme** [comment]
I haven't actually tried out `pgh3`, but I have looked at the code and I can list some differences:

* We have bindings to the current H3 core API (3.6.0), I think `pgh3` is around 3.4.0
* I notice `pgh3` does some cool stuff with memory allocation, possibly allowing more memory to be allocated for large polyfills (we should look more into that)
* We use a custom type for H3 indexes which will allow us to make custom indexes (e.g GiST support #7)
* We pull and statically link h3 during `make` while `pgh3` dynamically links to the system installation of h3
* We distribute `h3-pg` on PGXN which allows installation using `pgxn install h3`.

The best way to figure out which is best would be to try them both out ;-)

If you find anything missing in `h3-pg` you are more than welcome to open a pull request.
