### ISSUE TITLE
Build using release flag --> 2x/3x performance

### ISSUE THREAD

**Issue by AbelVM** [bytesandbrains/h3-pg#28]
As mentioned at https://github.com/bytesandbrains/h3-pg/issues/23#issuecomment-604582345 , adding `-DCMAKE_BUILD_TYPE=Release` to the makefile results in show 2x/3x improvements as per @Komzpa 's benchmarks at https://github.com/uber/h3/pull/326 

Current

```
kom@nucat:~/proj/h3/build$ bin/benchmarkH3Api 
        -- geoToH3: 1.187343 microseconds per iteration (10000 iterations)
        -- h3ToGeo: 0.796665 microseconds per iteration (10000 iterations)
        -- h3ToGeoBoundary: 2.219408 microseconds per iteration (10000 iterations)
```

With Release flag

```
kom@nucat:~/proj/h3/build$ bin/benchmarkH3Api
        -- geoToH3: 0.517386 microseconds per iteration (10000 iterations)
        -- h3ToGeo: 0.295042 microseconds per iteration (10000 iterations)
        -- h3ToGeoBoundary: 1.496694 microseconds per iteration (10000 iterations)
```

Latest build v3.6.2 does not use this flag

**Comment by zachasme** [comment]
I'll get right on it.

Focus for v3.6.2 was making `h3index` pass-by-value on supported systems.

**Comment by AbelVM** [comment]
Will it be released as a v3.6.2 hotfix or should we wait till v3.6.3? :yum:

**Comment by zachasme** [comment]
I'm about to release it as v3.6.3 :rocket:

**Comment by AbelVM** [comment]
BOOM :boom:

**Comment by Komzpa** [comment]
Please please check it with objdump that it all indeed inlined in final build. I had issues with it and couldn't do it for unknown for me reason.

**Comment by zachasme** [comment]
I'm going to keep your original issue open @Komzpa until we figure out how to get h3 inlined.

For now the performance improvements from release flag is worth a release.
