### ISSUE TITLE
Hashing error

### ISSUE THREAD

**Issue by AbelVM** [bytesandbrains/h3-pg#37]
When trying to use hashing on `h3index`, Posrtgres returns an error

```sql
CREATE TABLE hashtemp (  
        h3_id h3index PRIMARY KEY
) PARTITION BY HASH (h3_id);	
```

Returns:

`ERROR:  operator class "hash_h3index_ops" of access method hash is missing support function 2 for type h3index`

Bu [this](https://github.com/bytesandbrains/h3-pg/blob/master/sql/install/12-opclass_hash.sql) looks good to me... :thinking:

**Comment by zachasme** [comment]
I just checked the documentation again, and apparently [hash indexes allow a second support function](https://www.postgresql.org/docs/current/xindex.html#XINDEX-HASH-SUPPORT-TABLE).

I'll have to read up on that.
