### ISSUE TITLE
Immutable functions in GENERATED columns fail

### ISSUE THREAD

**Issue by AbelVM** [bytesandbrains/h3-pg#38]
Using `GENERATED` columns using `h3-pg` functions fail with this message, but the functions are actually IMMUTABLE (as well as [the wrapped ones](https://github.com/bytesandbrains/h3-pg/blob/master/sql/install/01-indexing.sql)):

`ERROR:  generation expression is not immutable`

Examples:

```sql
CREATE TABLE generatetemp (  
	h3_id h3index ,
        geom geometry(Point, 4326) GENERATED ALWAYS AS (h3_to_geometry(h3_id)) STORED	
) ;	
```
Function: https://github.com/bytesandbrains/h3-pg/blob/master/sql/install/99-postgis.sql#L30

```sql
CREATE TABLE generatetemp (  
	geom geometry(Point, 4326),
	h3_id h3index GENERATED ALWAYS AS (h3_geo_to_h3(geom, 10)) STORED	         
) ;	
```

Function: https://github.com/bytesandbrains/h3-pg/blob/master/sql/install/99-postgis.sql#L22

**Comment by zachasme** [comment]
This is probably because we forgot to include an upgrade-path in bd526aad91dd45d956babc387a045deb1f136fae.

We should mark `IMMUTABLE STRICT PARALLEL SAFE` in an upgrade-file.
