### ISSUE TITLE
Upgrade to H3 core 3.7.2

### ISSUE THREAD

**Issue by AbelVM** [bytesandbrains/h3-pg#50]
This version improves memory management when performing polyfill operations

**Comment by zachasme** [comment]
Has 3.7.2 been released yet? As far as I can tell 3.7.1 is the latest version.

But I can see that I've forgotten to release a version with 3.7.1 as well, I'll make sure to do that.

**Comment by AbelVM** [comment]
I was looking at the `h3-js` repo!!! :facepalm: 

https://github.com/uber/h3-js/releases

**Comment by zachasme** [comment]
No problem, at least I got around to releasing a version with h3 core 3.7.1 😄
