### ISSUE TITLE
pg_upgradecluster from 11 to 12 -k: H3index fields migrated with addresses instead of values

### ISSUE THREAD

**Issue by ArnaudSwail** [bytesandbrains/h3-pg#57]
pg 11 h3 3.6.1 -> pg 12 h3 3.6.1
We've noticed that H3Index values are not kept in H3Index type fields when upgrading from PG-11 to PG-12 with -m upgrade -k options. (no upgrade to 3.7.1 made, before or after migration)

**Comment by ArnaudSwail** [comment]
Not related to linked migration from pg11 to pg12 (needed since no disk space for full dump/restore).

After further tests, staying on pg11 and applying a new pgxn install h3 upgrading to 3.7.1, data got corrupted, returning the address of data instead of the data itself.

As pointed by nmandery:
https://github.com/bytesandbrains/h3-pg/blob/dd83e80a85cf1f02a836e51e4a774f21ecb27143/h3/sql/updates/h3--3.6.1--3.6.2.sql#L28

Same issue as https://github.com/bytesandbrains/h3-pg/issues/31

**Comment by zachasme** [comment]
Yes we still haven't found a way to help users migrate their data from pass-by-reference to pass-by-value. :-(
