### ISSUE TITLE
h3_line function output

### ISSUE THREAD

**Issue by rtpsr** [bytesandbrains/h3-pg#58]
Hi, 

I am trying to check the output that comes from h3_line function when a user draws a line. First step is to identify hexes at start and end point and then get hexes in the middle using h3_line function.

Sample hex 13s of interest '8d2674518d7133f','8d2674518d6347f'
Sample Output
![h3_line](https://user-images.githubusercontent.com/43997841/127709547-a6104308-8f77-4e07-95f7-781d16ad124e.PNG)

1) For the green line, the output from h3_line looks good.
2) For the blue line, the output from h3_line does not look correct. Is there a reliable way to get the overlapping hexes using h3 api? I understand that we can run a spatial query but trying to see if we have anything in h3 directly. Please advise.

Thanks!

**Comment by dfellis** [comment]
Minor quibble from me on "For the blue line, the output from h3_line does not look correct."

The `h3Line` function works in grid space. The origin and destination points are converted to H3 cells of the desired resolution and then a path is traced between them in the grid space. From that perspective, the blue line starts and ends in the same H3 cells as the green line, so they are functionally equivalent at the grid resolution you've chosen.

Basically, if you made your line width as thick as the hexagons are across, you'd see the blue and green lines overlap each other on the map, and if you consider the hexagon resolution that you've chosen the smallest "pixel" you're dealing with, the error is understandable.

But I do understand that that's not the effect you're going for; you want all of the hexagons that intersect the specified line, which is a different need.

H3 doesn't have a function for that (yet?) but you can approximate it by doing the following three steps:

1. Run `h3Line` between the two points at a much higher resolution (ideally resolution 15, but even just 2 resolutions finer than this ought to work).
2. Run `h3ToParent` on each of the resulting hexagons to bring it back to the desired resolution.
3. Remove duplicates with a Set operation. In `h3-pg` that'd be a `select distinct ...`

If your hexagons are already resolution 14 or 15 then this approach won't work, but for the rest that *should* be what you need.

**Comment by rtpsr** [comment]
Hi @dfellis ,

Thanks for your response. When I meant, "For the blue line, the output from h3_line does not look correct.", it is for my use case, not an issue with the library.

Going 2 resolutions higher, h3toParent,then a distinct did solve to get the right hexes under the line. I understand that it will not work for 14 or 15 resolutions. One question still remains is that, h3line gives the hexes in order, is there a way to get them in order along the line using this approach?  

Thanks!

**Comment by dfellis** [comment]
Hmm... Probably have the first `h3Line` call in an inner select that also grabs the [`ROW_NUMBER()`](https://www.postgresqltutorial.com/postgresql-row_number/) as a second column, then perform the `h3ToParent` on that result and keep the row number around, then select distinct on the H3 index but order by the row number. (I don't remember if postgres will let you do that in one shot (eg, order by a column you aren't selecting on) or if that needs to be another inner select for the select distinct and the next inner select has the order by clause and a final outer select drops the row numbers.)

**Comment by zachasme** [comment]
I'm going to close the issue. For now it's possible to use the workaround posted by @dfellis (thanks!) in https://github.com/bytesandbrains/h3-pg/issues/58#issuecomment-890218654.

If anyone needs a dedicated function/flag for this use-case, I recommend opening an issue upstream at uber/h3
