### ISSUE TITLE
point in polygon : point count is erroneous as half of the hex lies outside of polygon

### ISSUE THREAD

**Issue by rahulbreezo** [bytesandbrains/h3-pg#63]
Hi , 

My use case is to find points in polygon and show counts. 
I am solving this using making hex of certain resoltion  and club points then use centroid of that hex to find in which polygon it exist.
 
Below code is basically main logical part to check if  `center`(centroid of hex) exist in polygon or not

`h3_fire_idx ON ST_WITHIN(center, "Shapes"."shape_simplified_5")`

Problem is sometime a hex centroid exists in polygon but remaining half of hex exists outside of polygon , end up giving me wrong counts of points in polygon.

Is there any way to reduce this error without changing resolution of all the hex? Like can I dynamically split one big hex that is on the edge of polygon to multiple smaller hex and then get count from smaller hex. I think that will be more accurate.
All this should happen in one psql query.

Thanks,

**Comment by zachasme** [comment]
Hi rahul! If you haven't already I would take a look at the polyfill and compact functions. I would also try some of the more official H3 sources:

 * Posting to the [H3 tag on StackOverflow](https://stackoverflow.com/questions/tagged/h3)
 * There is also an [H3 Slack workspace](https://join.slack.com/t/h3-core/shared_invite/zt-g6u5r1hf-W_~uVJmfeiWtMQuBGc1NNg)

I'm afraid that's all the help I can offer :-) Feel free to open another issue or PR if you find any bugs or other problems.
