### ISSUE TITLE
v4 arm build

### ISSUE THREAD

**Issue by DeoLeung** [bytesandbrains/h3-pg#77]
Hi,

I'm building the new v4 for arm and there's some change in `Makefile` I'm not quite familiar

https://github.com/bytesandbrains/h3-pg/blob/master/Makefile#L70 defined but not used
https://github.com/bytesandbrains/h3-pg/blob/master/Makefile#L88

on my armv8
```bash
cc: error: unrecognized command-line option ‘-mpc64’
```
any other flags I need to change it to or just remove it?

**Comment by zachasme** [comment]
You should be able to just remove it, it was added as part of #75.

According to @mngr777:

> Without -mpc64, LTO (inlining specifically?) causes subtle differences in floating point calculation results on x86, several tests failing for both h3-pg and h3 library. 

This issues does raise the question of how to handle compilation flags for different architectures. Do you have any input @mngr777?

**Comment by mngr777** [comment]
@zachasme 
I think we can assume that `pg_config --cc` uses the same compiler that PGXS uses, so flags can be checked on test input file.
If `gcc -mpc64 test.c` fails, then the flag won't be added to CFLAGS.

**Comment by zachasme** [comment]
That's a good solution, thanks for the PR.
