### ISSUE TITLE
Should allow casting to bigint

### ISSUE THREAD

**Issue by kmacdough** [bytesandbrains/h3-pg#9]
H3 is carefully designed to fit within a 64-bit integer. It would be awesome if this extension at least supported storing an H3Index as such an integer for both storage, speed and manipulation purposes. 

It's a bit surprising that it's not the default, but seeing you're already on v3 with strings that might be a difficult change.

I'm not a postgres wizard and it's possible you're already doing this, but it seems unlikely:
```
# SELECT h3_geo_to_h3(POINT('37.3615593,-122.0553238'), 10)::bigint;
ERROR:  cannot cast type h3index to bigint
LINE 1: ... h3_geo_to_h3(POINT('37.3615593,-122.0553238'), 10)::bigint;
                                                              ^
# SELECT h3_geo_to_h3(POINT('37.3615593,-122.0553238'), 10)::char(16);
   h3_geo_to_h3
------------------
 8ae35e703307fff
(1 row)
```

**Comment by kmacdough** [comment]
Pardon my incompetence. Looks like you do already store as int-based. The GiST branch also looks like it includes a number of helpful features as well. 

Still not clear on how to get said int representation, but that's likely an issue with my Postgres knowledge. Currently attempting to avoid custom column types since it explodes Rails schema dump.

Closing since my issues are not yours.

**Comment by zachasme** [comment]
No problem, I do think you are right that it should be easier to get the bigint representation and it shouldn't be too hard to allow the cast you suggested. :+1: 

I'll re-open the issue and rename it accordingly.
